language: dart
dart:
  - dev

jobs:
  include:
    - stage: analyze_and_format
      name: "Analyze lib/"
      dart: dev
      os: linux
      script: dartanalyzer --fatal-warnings --fatal-infos lib/
    # Dirs outside of `lib` are not supported by allowed_experiments.json
    - stage: analyze_and_format
      name: "Analyze test/"
      dart: dev
      os: linux
      script: dartanalyzer --enable-experiment=non-nullable --fatal-warnings --fatal-infos test/
    - stage: analyze_and_format
      name: "Format"
      dart: dev
      os: linux
      script: dartfmt -n --set-exit-if-changed .
    - stage: test
      name: "Vm Tests"
      dart: dev
      os: linux
      script: pub run --enable-experiment=non-nullable test -p vm 
    - stage: test
      name: "Web Tests"
      dart: dev
      os: linux
      script: pub run --enable-experiment=non-nullable test -p chrome

stages:
  - analyze_and_format
  - test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master, null_safety]

cache:
 directories:
   - $HOME/.pub-cache
