language: dart
dart:
  - dev

dart_task:
  - test: -p vm
  # TODO: reinstate once https://github.com/dart-lang/typed_data/issues/16 is fixed
  # - test: -p firefox
  - dartfmt
  - dartanalyzer

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
