# https://dart.dev/tools/analysis
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_returning_null
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - no_adjacent_strings_in_list
    - package_api_docs
